import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "@/components/Navbar";
import { Flex } from "@chakra-ui/react";
import { CenterStorageProvider } from "@/context/CenterStorage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <CenterStorageProvider>
            <Navbar />
            <Flex
              p={{ base: "16px", md: "32px" }}
              w="100%"
              maxW="1280px"
              margin={"auto"}
            >
              {children}
            </Flex>
          </CenterStorageProvider>
        </Providers>
      </body>
    </html>
  );
}
